


# The CSV file to store and (in CSV mode) read the input data
dataFile: ../data/inputData.csv

# The directory where source images are stored or downloaded to
imageDirectory: ../data/images

# The CSV file for the segmentation result
outputCSV: ../output/pages.csv

# The directory to store Output Trig files
trigDirectory: ../output/trig

# Operation mode
# ---
# SPARQL : Query data from a SPARQL endpoint (configuration below)
# CSV : Read data from CSV file (configuration below)
mode: SPARQL

# The endpoint to execute the query when in SPARQL mode
endpoint: http://localhost:7778/blazegraph/sparql

# The SPARQL Query (when in SPARQL mode)
# ---
# The SPARQL Query should bind to
# ?id : unique identifier (will also used as file name to store the images)
# ?image : the IIIF Image API URL of the image
# ?width : (optional) the width of the image in its original size
# ?height : (optional) the height of the image in its original size
query: '
    PREFIX dcterms: <http://purl.org/dc/terms/>
    PREFIX la: <https://linked.art/ns/terms/>
    PREFIX search: <https://platform.swissartresearch.net/search/>
    PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
    
    SELECT ?id ?image ?width ?height WHERE {
      ?subject a search:Object ;
        crm:P128_carries/la:digitally_shown_by/la:digitally_available_via ?iiif . 
      ?iiif dcterms:conformsTo <http://iiif.io/api/image> ;
            la:access_point ?image .
      BIND(STRAFTER(STR(?subject), "https://resource.swissartresearch.net/artwork/") as ?id)
  } ORDER BY ?id'
